name: PortaNexus Android APK Build and Release
on:
  push:
    tags: [ 'v*.*.*' ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Android app
        run: eas build --platform android --local --non-interactive --profile preview --output "${{ github.workspace }}/portanexus-${{ github.ref_name}}.apk"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: portanexus-${{ github.ref_name}}.apk
          path: ${{ github.workspace }}/portanexus-${{ github.ref_name}}.apk

      - name: Upload APK to Release Tag
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "${{ github.workspace }}/portanexus-${{ github.ref_name }}.apk"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name}}